language: ruby
rvm:
  - 2.0.0
  - 2.1.1
before_script:
  - cd spec/dummy
  - RAILS_ENV=development bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
script: ./travis.sh
notifications:
  email: false
